---
- name: Delete .txt, .php, and .log files in a given directory on Windows
  hosts: windows
  gather_facts: no
  tasks:
    - name: Remove .txt, .php, and .log files from the directory
      win_find:
        paths: "E:\Logs"  # Replace with the actual directory path
        patterns:
          - "*.txt"
          - "*.php"
          - "*.log"
        recurse: yes  # Include subdirectories if needed
      register: files_to_delete

    - name: Delete the found files
      win_file:
        path: "{{ item.path }}"
        state: absent
      loop: "{{ files_to_delete.files }}"
      when: files_to_delete.matched > 0
